---
- name: Setup Ollama Web UI
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create ollama directory
      file:
        path: /home/ubuntu/ollama
        state: directory
        mode: '0755'

    - name: Clone the repository
      git:
        repo: 'https://github.com/Nataliavino/ollama.git'
        dest: /home/ubuntu/ollama
        version: main

    - name: Install Ollama
      shell: |
        curl https://ollama.ai/install.sh | sh
      args:
        creates: /usr/local/bin/ollama

    - name: Start Ollama service
      systemd:
        name: ollama
        state: started
        enabled: yes

    - name: Create .ollama directory
      file:
        path: /home/ubuntu/.ollama
        state: directory
        mode: '0755'

    - name: Pull Ollama Web UI Docker image
      docker_image:
        name: ghcr.io/ollama-webui/ollama-webui:main
        source: pull

    - name: Run Ollama Web UI Docker container
      docker_container:
        name: ollama-webui
        image: ghcr.io/ollama-webui/ollama-webui:main
        state: started
        restart_policy: always
        ports:
          - "80:8080"
        volumes:
          - /home/ubuntu/.ollama:/root/.ollama
        env:
          OLLAMA_API_BASE_URL: "http://localhost:11434/api"
