---
- name: Setup Chat UI Application
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - nodejs
          - npm
        state: latest

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Install Docker Module for Python
      apt:
        name: python3-docker
        state: present

    - name: Create application directory
      file:
        path: /home/ubuntu/chat-ui
        state: directory
        mode: '0755'

    - name: Clone the repository
      git:
        repo: 'https://github.com/Nataliavino/ollama.git'
        dest: /home/ubuntu/chat-ui
        version: main

    - name: Install npm dependencies
      npm:
        path: /home/ubuntu/chat-ui

    - name: Build the Next.js application
      command: npm run build
      args:
        chdir: /home/ubuntu/chat-ui

    - name: Start the Next.js application
      command: npm start
      args:
        chdir: /home/ubuntu/chat-ui
      async: 1000
      poll: 0

    - name: Ensure application is reachable
      wait_for:
        port: 80
        delay: 10
        timeout: 300
